# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poblacion', models.CharField(help_text='Requerido. 30 carácteres como máximo.', max_length=30)),
                ('telefono', models.CharField(blank=True, help_text='Opcional. 9 dígitos como máximo. Debe comenzar por 6 ó 9.', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono no cumple con el patrón solicitado.', regex='^(6|9)(\\d{8})$')])),
                ('direccion', models.CharField(blank=True, help_text='Opcional. 50 carácteres como máximo.', max_length=50, null=True)),
                ('imagen', models.URLField(blank=True, help_text='Opcional. URL a la imagen en formato PNG, JPG o JPGE.', null=True, validators=[django.core.validators.RegexValidator(message='La URL no corresponde con una imagen en formato especificado.', regex='((.png)|(.jpg)|(.jpge))$')], verbose_name='Imagen de perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Actor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Administradores',
            },
            bases=('usuarios.actor',),
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Actor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('usuarios.actor',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.Actor')),
                ('categorias', models.ManyToManyField(to='categorias.Categoria')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('usuarios.actor',),
        ),
    ]
