# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 13:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20171216_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='imagen',
            field=models.URLField(default='http://i68.tinypic.com/4fwz6h.png', help_text='Opcional. URL a la imagen en formato PNG, JPG o JPGE.', null=True, validators=[django.core.validators.RegexValidator(message='La URL no corresponde con una imagen en formato especificado.', regex='((.png)|(.jpg)|(.jpge))$')], verbose_name='Imagen de perfil'),
        ),
    ]
