# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20171228_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name_plural': 'Actores'},
        ),
    ]
