# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 14:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_auto_20171228_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='usuario',
            field=models.OneToOneField(help_text='Recuerde que es necesario crear un usuario al que asignar la cuenta del funcionario.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
