# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Corpus',
            },
        ),
        migrations.CreateModel(
            name='EntradaCorpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(help_text='Formato recomentado: título, salto de línea y cuerpo.', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Entradas corpus',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('corpus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='corpus.Corpus')),
            ],
        ),
        migrations.AddField(
            model_name='entradacorpus',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.Corpus'),
        ),
    ]
