# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradacorpus',
            name='texto',
            field=models.TextField(help_text='Formato recomentado: título, salto de línea y cuerpo.', max_length=6000),
        ),
    ]
