# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_corpus_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='nombre',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
