# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('corpus', '0004_auto_20171205_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradacorpus',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria', verbose_name='Categorización'),
        ),
    ]
