# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-22 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_auto_20180109_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='ruta',
            field=models.FilePathField(editable=False, null=True, verbose_name='C:/Proyectos/AlcaldeEscuchame/AlcaldeEscuchame/AlcaldeEscuchame/static/corpus/modelo.npy'),
        ),
    ]
