# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.URLField(blank=True, help_text='Opcional. URL a la imagen en formato PNG, JPG o JPGE.', null=True, validators=[django.core.validators.RegexValidator(message='La URL no corresponde con una imagen en formato especificado.', regex='((.png)|(.jpg)|(.jpge))$')], verbose_name='Imagen de perfil')),
                ('nombre', models.CharField(help_text='Requerido. 80 carácteres como máximo.', max_length=80)),
                ('descripcion', models.TextField(help_text='Requerido. 300 carácteres como máximo.', max_length=300)),
            ],
        ),
    ]
