# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 10:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(help_text='Requerido. 7 carácteres que cumplan el patrón: dos letras, un guión y cuatro caracteres (letras o dígitos). Ejemplo: QU-1aZ9', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='La referencia no cumple el patrón solicitado.', regex='^([a-zA-Z]{2})-([a-zA-Z0-9]{4})$')])),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha de publicación')),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField(max_length=1000)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Tramitada', 'Tramitada')], default='Abierta', max_length=10)),
                ('categoriaAutomatica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categorias.Categoria', verbose_name='Categorización Automática')),
                ('categoriaManual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria', verbose_name='Categorización Manual')),
                ('ciudadano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Ciudadano')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(help_text='Requerido. Rango de 0 a 5 (inclusives).', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('ciudadano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Ciudadano')),
                ('queja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quejas.Queja')),
            ],
            options={
                'verbose_name_plural': 'Valoraciones',
            },
        ),
        migrations.AddField(
            model_name='queja',
            name='votantes',
            field=models.ManyToManyField(related_name='votantes', through='quejas.Valoracion', to='usuarios.Ciudadano'),
        ),
    ]
