# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='cuerpo',
            field=models.TextField(max_length=5000),
        ),
    ]
