# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('quejas', '0002_auto_20171202_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together=set([('ciudadano', 'queja')]),
        ),
    ]
